### ISSUE TITLE
Add a possibility to have a i3-gaps binary

### ISSUE THREAD

**Issue by rapha8l** [maestrogerardo/i3-gaps-deb#3]
Hi,

Thanks a lot for your work
Maybe,  it could be an interesting option to have the name i3-gaps to binaries and everything (possible with --program-suffix at configure time), if one want to have both i3 and i3-gaps (even if the config file problem remains)

Have a nice day

**Comment by maestrogerardo** [comment]
Hi @rapha8l ,

yeah, I also like the idea. I'm already struggling a bit with this approach (and other ideas)... but I'm still not sure which way to go at the end.

Using the (current) build setup (which seems to be "original" w/ some minor modifications from my side), we get a lot of binaries (which are finally installed via the Debian package), see:

```
# dpkg -L i3-wm | grep bin/
/usr/bin/i3
/usr/bin/i3-config-wizard
/usr/bin/i3-dmenu-desktop
/usr/bin/i3-dump-log
/usr/bin/i3-input
/usr/bin/i3-migrate-config-to-v4
/usr/bin/i3-msg
/usr/bin/i3-nagbar
/usr/bin/i3-save-tree
/usr/bin/i3-sensible-editor
/usr/bin/i3-sensible-pager
/usr/bin/i3-sensible-terminal
/usr/bin/i3bar
/usr/bin/i3-with-shmlog
```

So, I think renaming everything is not the ideal approach. First, users might be used to some commands for years (e.g. using `i3-msg-gaps` instead of `i3-msg` to do the same thing, seems wired). Second, there are a lot of manpages and documentation, which then also have to be updated (and maintained).

Furthermore I guess that also the (upstream) author's thought is to replace i3 (if gaps are desired). Otherwise, the code (and/or buildsystem) might look a lot different...

Anyway, I'm currently working on some things/improvements regarding "i3-gaps on Debian". Stay tuned (even if it could take a while)... :-)

**Comment by rapha8l** [comment]
I agree, it's not a simple problem :-) 
Thanks, I'll stay tuned

**Comment by Airblader** [comment]
Just popping in: it's also not that easy because things like i3-nagbar are hardcoded inside i3, so you'd have to actually patch the code first.

**Comment by kafran** [comment]
Why have both? Just adjust the gaps to 0 and you have i3 =). Actually I really don't understand why the i3 developers are so "stubborn" and doesn't implement this upstream as 99% of i3 users seems to use gaps as it improves readability.

**Comment by Airblader** [comment]
> Actually I really don't understand why the i3 developers are so "stubborn" and doesn't implement this upstream

I have explained this many, many times in various places.

**Comment by Airblader** [comment]
> as 99% of i3 users seems to use gaps 

Also, this is a nice made-up statistic which is of course completely wrong.

**Comment by kafran** [comment]
> I have explained this many, many times in various places.

Can you give me a link? I would like to read. The only explanation someone gave me once was: i3 was made to use all the available space.

Yep, I agree with the made-up statistics ;p but it's just what I see on Reddit, it's hard to see someone with upstream i3.

**Comment by Airblader** [comment]
> Can you give me a link?

It boils down to two things:

1. The way gaps are implemented is more of a hack (which is why titlebars don't work), so we would just never consider merging it upstream due to the quality of the patch.
2. Michael decided that gaps don't fit his idea of what i3 stands for and should be, and I fully respect this decision.

GIven how easy it is to install i3-gaps I frankly don't understand why people keep complaining about this decision. If your distribution is missing a proper package for i3-gaps, that is not an issue of i3 but rather a shortcoming of the community of your distribution. Just be the good guy and create a package for it.

> but it's just what I see on Reddit, it's hard to see someone with upstream i3.

And by reddit you probably mostly mean /r/unixporn, right? ;-) Trust me, there are many more i3 users than i3-gaps users out there.

**Comment by rapha8l** [comment]
Hi, maybe it was not such a good idea, I can close if you prefer

**Comment by dalechyn** [comment]
As i3-gaps already coming to the i3, it is irreleveant

**Comment by rapha8l** [comment]
I don't understand much the last comment, but anyway I think afterwards that the request may not be much relevant. I'll close it
And thanks to Airblader for answering
