### ISSUE TITLE
Aptitude installs i3 over the top of i3-gaps

### ISSUE THREAD

**Issue by JMMackenzie** [maestrogerardo/i3-gaps-deb#34]
As the title suggests, I can install `i3-gaps` with your tool but once I run `sudo apt-get dist-upgrade` the system reinstalls `i3` over the top. Do you have any suggestions on how I can fix this?

Thanks for the great package, by the way!

**Comment by maestrogerardo** [comment]
Hi JMMackenzie,

I don't know your system (nor the branch you 're using to build i3-gaps with this tool), but I guess that the version of your package manager is simply greater then the version you're building yourself with i3-gaps-deb.

So, if you're using the "gaps" branch, than switching to "gaps-next" (inside of i3-gaps-deb) might solve your problem.

Otherwise, using APT's pinning facilities might help you out: https://wiki.debian.org/AptConfiguration#apt_preferences_.28APT_pinning.29

Cheers.

**Comment by JMMackenzie** [comment]
Thanks, using `gaps-next` solved this issue.
